import type { Component } from 'vue'
import {
  LuActivity,
  LuAlertTriangle,
  LuBell,
  LuBot,
  LuBrain,
  LuClock3,
  LuCornerDownLeft,
  LuCpu,
  LuDatabase,
  LuFileEdit,
  LuFileText,
  LuGitBranch,
  LuGitFork,
  LuGlobe2,
  LuHelpCircle,
  LuImage,
  LuLayers3,
  LuListChecks,
  LuMessageSquareReply,
  LuMessageSquareText,
  LuNavigation,
  LuPlay,
  LuSearch,
  LuSlidersHorizontal,
  LuSparkles,
  LuTerminalSquare,
  LuUserRoundCog,
  LuUsers,
  LuWrench,
} from 'vue-icons-plus/lu'
import type { SignalNodeVisualKind } from '../graph/executionPresentation'

/**
 * Horizontal Signal icons use one coherent Lucide stroke family from vue-icons-plus.
 * The renderer mounts each component once into a detached SVG host and turns it into
 * a reusable monochrome Pixi texture; node instances only select and tint sprites.
 */
export const SIGNAL_NODE_ICONS: Record<SignalNodeVisualKind, Component> = {
  start: LuPlay,
  input: LuMessageSquareText,
  reply: LuMessageSquareReply,
  error: LuAlertTriangle,
  fold: LuLayers3,
  process: LuActivity,
  dispatch: LuGitFork,
  return: LuCornerDownLeft,
  system: LuCpu,
  'tool-command': LuTerminalSquare,
  'tool-read': LuFileText,
  'tool-write': LuFileEdit,
  'tool-search': LuSearch,
  'tool-skill': LuSparkles,
  'tool-spawn': LuBot,
  'tool-child': LuUsers,
  'tool-question': LuHelpCircle,
  'tool-media': LuImage,
  'tool-todo': LuListChecks,
  'tool-memory': LuBrain,
  'tool-config': LuSlidersHorizontal,
  'tool-navigate': LuNavigation,
  'tool-role': LuUserRoundCog,
  'tool-web': LuGlobe2,
  'tool-data': LuDatabase,
  'tool-git': LuGitBranch,
  'tool-time': LuClock3,
  'tool-notify': LuBell,
  'tool-generic': LuWrench,
}
