import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  handleSoulCreate,
  handleSoulDelete,
  handleSoulList,
  handleSoulLoad,
  registerSoulHandlers,
  agentSouls,
} from "@/service/soul/lifecycle.js";
import type { HandlerContext } from "@/service/message/router.js";
import { Method, createError } from "@/service/message/types.js";

// Mock dependencies
vi.mock("@/agent/builder.js", () => {
  function MockAgentBuilder(this: any) {
    this.use = vi.fn().mockReturnThis();
    this.build = vi.fn().mockResolvedValue({
      createChat: vi.fn(),
      send: vi.fn(),
    });
  }
  return {
    AgentBuilder: MockAgentBuilder,
  };
});

vi.mock("@/utils/config", () => ({
  default: {
    llm: {
      brain: {
        testBrain: { provider: "ollama", model: "test-model", sense_group: ["safe"] },
        anotherBrain: { provider: "openai", model: "gpt-4" },
      },
    },
  },
}));

vi.mock("@/db/soul.js", () => ({
  createSoul: vi.fn(),
  getSoul: vi.fn(),
  listSouls: vi.fn(),
  deleteSoul: vi.fn(),
  parseSoulRow: vi.fn(),
}));

vi.mock("@/db/chat.js", () => ({
  listChatsBySoul: vi.fn(),
  getMessages: vi.fn(),
}));

vi.mock("@/db/approval.js", () => ({
  approvalRepo: {
    findBySoulId: vi.fn(),
  },
}));

import { AgentBuilder } from "@/agent/builder.js";
import { createSoul, getSoul, listSouls, deleteSoul, parseSoulRow } from "@/db/soul.js";
import { listChatsBySoul, getMessages } from "@/db/chat.js";
import { approvalRepo } from "@/db/approval.js";

function createMockCtx(): HandlerContext {
  return {
    connectionId: "conn-1",
    sendChunk: vi.fn(),
    sendNotification: vi.fn(),
    soulId: undefined,
  };
}

describe("handleSoulCreate", () => {
  let mockCtx: HandlerContext;

  beforeEach(() => {
    vi.clearAllMocks();
    mockCtx = createMockCtx();
    agentSouls.clear();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  it("should create new soul and store in memory", async () => {
    vi.mocked(getSoul).mockReturnValue(null);
    vi.mocked(createSoul).mockReturnValue({
      id: "soul-1",
      created_at: 1000,
    } as any);

    const result = await handleSoulCreate(mockCtx, {
      brain: "testBrain",
      soulId: "soul-1",
    });

    expect(result).toEqual({
      soulId: "soul-1",
      config: {
        provider: "ollama",
        model: "test-model",
        sense_group: ["safe"],
      },
      createdAt: 1000,
    });

    expect(agentSouls.has("soul-1")).toBe(true);
    expect(mockCtx.soulId).toBe("soul-1");
  });

  it("should generate soulId if not provided", async () => {
    vi.mocked(getSoul).mockReturnValue(null);
    vi.mocked(createSoul).mockImplementation((id) => ({
      id,
      created_at: 1000,
    } as any));

    const result = await handleSoulCreate(mockCtx, {
      brain: "testBrain",
    });

    // soulId should be a UUID generated by crypto.randomUUID()
    expect(result.soulId).toMatch(/^[a-f0-9-]{36}$/);
  });

  it("should recover existing soul from database", async () => {
    vi.mocked(getSoul).mockReturnValue({
      id: "soul-1",
      agent_name: "testBrain",
      provider: "ollama",
      model: "test-model",
      sense_group: null,
      created_at: 2000,
    } as any);
    vi.mocked(parseSoulRow).mockReturnValue({
      agentName: "testBrain",
      provider: "ollama",
      model: "test-model",
      senseGroup: null,
      createdAt: 2000,
    });

    const result = await handleSoulCreate(mockCtx, {
      brain: "testBrain",
      soulId: "soul-1",
    });

    expect(result).toEqual({
      soulId: "soul-1",
      config: {
        provider: "ollama",
        model: "test-model",
        sense_group: null,
      },
      createdAt: 2000,
      recovered: true,
    });

    // Should not call createSoul for existing soul
    expect(createSoul).not.toHaveBeenCalled();
  });

  it("should throw error for non-existent brain config", async () => {
    vi.mocked(getSoul).mockReturnValue(null);

    await expect(
      handleSoulCreate(mockCtx, {
        brain: "nonExistentBrain",
        soulId: "soul-1",
      })
    ).rejects.toThrow('Brain "nonExistentBrain" 不存在');
  });
});

describe("handleSoulDelete", () => {
  let mockCtx: HandlerContext;

  beforeEach(() => {
    vi.clearAllMocks();
    mockCtx = createMockCtx();
    agentSouls.clear();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  it("should return error when soul has chats", async () => {
    vi.mocked(listChatsBySoul).mockReturnValue([{ id: "chat-1" }] as any);

    const result = await handleSoulDelete(mockCtx, { soulId: "soul-1" });

    expect(result).toEqual(createError("SOUL_HAS_CHATS", "Soul has chats, delete them first"));
  });

  it("should throw error when soul not found in memory or database", async () => {
    vi.mocked(listChatsBySoul).mockReturnValue([]);
    vi.mocked(getSoul).mockReturnValue(null);

    await expect(
      handleSoulDelete(mockCtx, { soulId: "non-existent" })
    ).rejects.toThrow('Soul "non-existent" not found');
  });

  it("should delete soul from memory and database", async () => {
    vi.mocked(listChatsBySoul).mockReturnValue([]);
    vi.mocked(deleteSoul).mockReturnValue(undefined);

    agentSouls.set("soul-1", {
      id: "soul-1",
      agent: Promise.resolve({}),
      config: { provider: "ollama", model: "test-model" },
      createdAt: 1000,
    });

    const result = await handleSoulDelete(mockCtx, { soulId: "soul-1" });

    expect(deleteSoul).toHaveBeenCalledWith("soul-1");
    expect(agentSouls.has("soul-1")).toBe(false);
    expect(result).toEqual({ soulId: "soul-1" });
  });

  it("should delete soul from database only when not in memory", async () => {
    vi.mocked(listChatsBySoul).mockReturnValue([]);
    vi.mocked(getSoul).mockReturnValue({
      id: "soul-1",
    } as any);
    vi.mocked(deleteSoul).mockReturnValue(undefined);

    const result = await handleSoulDelete(mockCtx, { soulId: "soul-1" });

    expect(deleteSoul).toHaveBeenCalledWith("soul-1");
    expect(result).toEqual({ soulId: "soul-1" });
  });
});

describe("handleSoulList", () => {
  let mockCtx: HandlerContext;

  beforeEach(() => {
    vi.clearAllMocks();
    mockCtx = createMockCtx();
  });

  it("should return empty array when no souls", async () => {
    vi.mocked(listSouls).mockReturnValue([]);

    const result = await handleSoulList(mockCtx, {});

    expect(result).toEqual({ souls: [] });
  });

  it("should return list of souls with config", async () => {
    vi.mocked(listSouls).mockReturnValue([
      { id: "soul-1", agent_name: "testBrain", provider: "ollama", model: "test-model", sense_group: null, created_at: 1000 },
      { id: "soul-2", agent_name: "anotherBrain", provider: "openai", model: "gpt-4", sense_group: "advanced", created_at: 2000 },
    ] as any);
    vi.mocked(parseSoulRow)
      .mockReturnValueOnce({
        agentName: "testBrain",
        provider: "ollama",
        model: "test-model",
        senseGroup: null,
        createdAt: 1000,
      })
      .mockReturnValueOnce({
        agentName: "anotherBrain",
        provider: "openai",
        model: "gpt-4",
        senseGroup: "advanced",
        createdAt: 2000,
      });

    const result = await handleSoulList(mockCtx, {});

    expect(result).toEqual({
      souls: [
        {
          soulId: "soul-1",
          config: { provider: "ollama", model: "test-model", sense_group: null },
          createdAt: 1000,
        },
        {
          soulId: "soul-2",
          config: { provider: "openai", model: "gpt-4", sense_group: "advanced" },
          createdAt: 2000,
        },
      ],
    });
  });
});

describe("handleSoulLoad", () => {
  let mockCtx: HandlerContext;

  beforeEach(() => {
    vi.clearAllMocks();
    mockCtx = createMockCtx();
    agentSouls.clear();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  it("should throw error when soul not found in database", async () => {
    vi.mocked(getSoul).mockReturnValue(null);

    await expect(
      handleSoulLoad(mockCtx, { soulId: "non-existent" })
    ).rejects.toThrow('Soul "non-existent" not found');
  });

  it("should load soul into memory and return info", async () => {
    vi.mocked(getSoul).mockReturnValue({
      id: "soul-1",
      agent_name: "testBrain",
      provider: "ollama",
      model: "test-model",
      sense_group: null,
      created_at: 1000,
    } as any);
    vi.mocked(parseSoulRow).mockReturnValue({
      agentName: "testBrain",
      provider: "ollama",
      model: "test-model",
      senseGroup: null,
      createdAt: 1000,
    });
    vi.mocked(listChatsBySoul).mockReturnValue([
      { id: "chat-1", created_at: 1000, updated_at: 2000 },
    ] as any);
    vi.mocked(getMessages).mockReturnValue([{ id: "m1" }] as any);
    vi.mocked(approvalRepo.findBySoulId).mockResolvedValue([]);

    const result = await handleSoulLoad(mockCtx, { soulId: "soul-1" });

    expect(result).toEqual({
      soulId: "soul-1",
      config: {
        provider: "ollama",
        model: "test-model",
        sense_group: null,
      },
      createdAt: 1000,
      chats: [
        {
          chatId: "chat-1",
          createdAt: 1000,
          updatedAt: 2000,
          messageCount: 1,
        },
      ],
      pendingApprovals: [],
    });

    expect(agentSouls.has("soul-1")).toBe(true);
    expect(mockCtx.soulId).toBe("soul-1");
  });

  it("should return pending approvals", async () => {
    vi.mocked(getSoul).mockReturnValue({
      id: "soul-1",
      agent_name: "testBrain",
      provider: "ollama",
      model: "test-model",
      sense_group: null,
      created_at: 1000,
    } as any);
    vi.mocked(parseSoulRow).mockReturnValue({
      agentName: "testBrain",
      provider: "ollama",
      model: "test-model",
      senseGroup: null,
      createdAt: 1000,
    });
    vi.mocked(listChatsBySoul).mockReturnValue([]);
    vi.mocked(getMessages).mockReturnValue([]);
    vi.mocked(approvalRepo.findBySoulId).mockResolvedValue([
      {
        id: "approval-1",
        chatId: "chat-1",
        status: "pending",
        createdAt: 1000,
        senseCalls: [{ id: "sc-1", name: "test", arguments: "{}", approved: false, triggeredAt: 1000 }],
      },
      {
        id: "approval-2",
        chatId: "chat-1",
        status: "completed",
        createdAt: 2000,
        senseCalls: [],
      },
    ] as any);

    const result = await handleSoulLoad(mockCtx, { soulId: "soul-1" });

    expect(result.pendingApprovals).toHaveLength(1);
    expect(result.pendingApprovals[0]).toEqual({
      approvalId: "approval-1",
      chatId: "chat-1",
      createdAt: 1000,
      senseCalls: [{ id: "sc-1", name: "test", arguments: "{}", approved: false, triggeredAt: 1000 }],
    });
  });

  it("should not create new agent if already in memory", async () => {
    // Pre-populate agentSouls
    agentSouls.set("soul-1", {
      id: "soul-1",
      agent: Promise.resolve({
        createChat: vi.fn(),
        send: vi.fn(),
      }),
      config: { provider: "ollama", model: "test-model" },
      createdAt: 1000,
    });

    vi.mocked(getSoul).mockReturnValue({
      id: "soul-1",
      agent_name: "testBrain",
      provider: "ollama",
      model: "test-model",
      sense_group: null,
      created_at: 1000,
    } as any);
    vi.mocked(parseSoulRow).mockReturnValue({
      agentName: "testBrain",
      provider: "ollama",
      model: "test-model",
      senseGroup: null,
      createdAt: 1000,
    });
    vi.mocked(listChatsBySoul).mockReturnValue([]);
    vi.mocked(getMessages).mockReturnValue([]);
    vi.mocked(approvalRepo.findBySoulId).mockResolvedValue([]);

    await handleSoulLoad(mockCtx, { soulId: "soul-1" });

    // AgentBuilder should not be called since soul already in memory
    // Note: AgentBuilder is not a spy, so we check that agentSouls still has the original entry
    expect(agentSouls.has("soul-1")).toBe(true);
  });
});

describe("registerSoulHandlers", () => {
  it("should register all handlers to router", () => {
    const router = {
      register: vi.fn(),
    } as any;

    registerSoulHandlers(router);

    expect(router.register).toHaveBeenCalledWith(Method.SOUL_CREATE, handleSoulCreate);
    expect(router.register).toHaveBeenCalledWith(Method.SOUL_DELETE, handleSoulDelete);
    expect(router.register).toHaveBeenCalledWith(Method.SOUL_LIST, handleSoulList);
    expect(router.register).toHaveBeenCalledWith(Method.SOUL_LOAD, handleSoulLoad);
  });
});