export { default as WorkbenchCapsule } from './WorkbenchCapsule.vue'
export { default as WorkbenchDialog } from './WorkbenchDialog.vue'
export { useLiteViewToggle } from './useLiteViewToggle'
export { useWorkbenchWindow } from './useWorkbenchWindow'
export type { ResizeDirection, WorkbenchMode } from './useWorkbenchWindow'
