import type { ServerResponse } from 'node:http'

export function writeManagerPage(res: ServerResponse, lanAccess: boolean): void {
  res.writeHead(200, {
    'Content-Type': 'text/html; charset=utf-8',
    'Cache-Control': 'no-store',
  })
  res.end(`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>CheryNyxus 本地管理器</title>
<style>
:root{color-scheme:light;--desktop:#17324b;--desktop-dark:#10263a;--window:#c0c0c0;--window-light:#fff;--window-shadow:#404040;--title:#082b78;--title-dark:#00144c;--ink:#111;--muted:#454545;--field:#fff;--blue:#000080;--green:#08752b;--yellow:#8b5a00;--red:#9b1717;--pixel:repeating-conic-gradient(#ffffff 0 25%,#d0d0d0 0 50%) 0/4px 4px}
*{box-sizing:border-box}html,body{min-height:100%;margin:0}body{padding:24px;background-color:var(--desktop);background-image:linear-gradient(135deg,rgba(255,255,255,.035) 25%,transparent 25%),linear-gradient(315deg,rgba(0,0,0,.09) 25%,transparent 25%);background-size:8px 8px;color:var(--ink);font:13px/1.35 Tahoma,"MS Sans Serif",Arial,sans-serif}
.window{max-width:1120px;margin:0 auto;background:var(--window);border:2px solid;border-color:var(--window-light) var(--window-shadow) var(--window-shadow) var(--window-light);box-shadow:3px 3px 0 rgba(0,0,0,.45);padding:3px}.titlebar{position:relative;display:flex;align-items:center;gap:7px;min-height:25px;padding:3px 4px;color:#fff;background:linear-gradient(90deg,var(--title),#1d53a8 58%,var(--title-dark));font-weight:700;overflow:hidden}.titlebar:after{content:"";position:absolute;inset:0 auto 0 42%;width:58%;opacity:.16;background:var(--pixel);mix-blend-mode:screen;animation:pixel-drift 8s steps(8,end) infinite}.app-icon{position:relative;z-index:1;width:15px;height:15px;border:1px solid #fff;background:#0a6b9f;box-shadow:inset 2px 2px #72d7e9,inset -2px -2px #00305b;flex:none}.title{position:relative;z-index:1;flex:1;white-space:nowrap}.window-controls{position:relative;z-index:1;display:flex;gap:2px}.window-controls button{width:19px;height:18px;padding:0;background:var(--window);color:#111;border:2px solid;border-color:#fff #404040 #404040 #fff;font:bold 12px/12px Arial;cursor:default}.window-controls button:active{border-color:#404040 #fff #fff #404040;padding:1px 0 0 1px}
.menubar{display:flex;gap:2px;padding:3px 5px;border-bottom:1px solid #808080}.menu-item{padding:2px 7px}.menu-item:first-letter{text-decoration:underline}.menu-item:hover{background:var(--blue);color:#fff}.warning{margin:7px;padding:7px 9px;border:2px solid;border-color:#808080 #fff #fff #808080;background:#ffffdf;color:#3d2d00}.warning strong{color:var(--yellow)}.content{padding:7px}.section{margin-bottom:9px;border:2px solid;border-color:#808080 #fff #fff #808080;background:var(--window);padding:4px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:3px 6px;background:#d4d0c8;border:1px solid #808080;border-bottom-color:#fff;margin-bottom:6px}.section-head h2{margin:0;font-size:13px}.section-label{font-size:11px;color:#444;text-transform:uppercase;letter-spacing:.05em}.overview{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.summary{min-height:92px;border:2px solid;border-color:#808080 #fff #fff #808080;background:#d4d0c8;padding:7px}.summary-title{display:flex;align-items:center;gap:6px;font-weight:700}.summary-value{margin-top:10px;color:var(--blue);font-size:19px;font-weight:700}.summary-detail{margin:3px 0 0;color:var(--muted)}.pixel-light{width:10px;height:10px;border:1px solid #333;background:#777;box-shadow:inset 1px 1px #fff;flex:none}.pixel-light.ok{background:#0b9b3d}.pixel-light.warn{background:#d18b00}.pixel-light.error{background:#c42020}.pixel-light.pulse{animation:status-pulse 700ms steps(2,end)}
.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.metric{min-height:75px;padding:6px;background:#d4d0c8;border:2px solid;border-color:#808080 #fff #fff #808080}.metric-label,.metric-note{display:block;color:#444}.metric-label{font-size:12px}.metric-value{display:block;margin:5px 0 1px;color:var(--blue);font:bold 20px "Courier New",monospace;letter-spacing:.04em}.metric-value.changed{animation:value-change 420ms steps(3,end)}.metric-note{font-size:11px}.meta{display:flex;flex-wrap:wrap;gap:4px 15px;margin:7px 2px 1px;color:#444;font-size:11px}.meta strong{color:#111;font-weight:400}.processes{display:flex;flex-wrap:wrap;gap:5px 14px;margin:6px 2px 0;padding:0;list-style:none}.processes li{display:flex;align-items:center;gap:4px}.processes li:before{content:"";width:7px;height:7px;background:#777;border:1px solid #333;box-shadow:inset 1px 1px #fff}.processes li.ok:before{background:#0b9b3d}.processes li.warn:before{background:#d18b00}
.credentials-grid{display:grid;grid-template-columns:minmax(0,1fr);gap:7px}.form-grid{display:grid;grid-template-columns:minmax(150px,.7fr) minmax(280px,1.3fr);gap:7px}.field{display:flex;flex-direction:column;gap:3px}.field label{font-weight:700}.field input{width:100%;height:24px;padding:2px 4px;background:var(--field);border:2px solid;border-color:#404040 #fff #fff #404040;color:#111;font:13px Tahoma,"MS Sans Serif",Arial,sans-serif}.password-row{display:flex;gap:5px}.password-row input{flex:1;min-width:0}.button-row{display:flex;justify-content:flex-end;gap:5px;margin-top:7px}.retro-button{min-height:24px;padding:2px 10px;background:var(--window);color:#111;border:2px solid;border-color:#fff #404040 #404040 #fff;font:13px Tahoma,"MS Sans Serif",Arial,sans-serif;cursor:pointer}.retro-button:hover{background:#d8d8d8}.retro-button:active{border-color:#404040 #fff #fff #404040;padding:3px 9px 1px 11px}.retro-button:focus-visible{outline:1px dotted #111;outline-offset:-4px}.primary{font-weight:700}.message{min-height:17px;margin:6px 0 0}.message.ok{color:var(--green)}.message.warn{color:var(--yellow)}.message.error{color:var(--red)}.statusbar{display:flex;gap:5px;padding:3px 4px;border-top:1px solid #808080}.status-cell{min-height:20px;padding:2px 7px;border:2px solid;border-color:#808080 #fff #fff #808080;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status-cell:first-child{flex:1}.status-cell:last-child{min-width:150px}.statusbar strong{font-weight:700}
@keyframes pixel-drift{0%{transform:translateX(0)}100%{transform:translateX(12px)}}@keyframes status-pulse{0%,100%{opacity:1}50%{opacity:.25}}@keyframes value-change{0%{opacity:.35;transform:translateY(-2px)}100%{opacity:1;transform:translateY(0)}}@keyframes window-enter{0%{opacity:0;transform:translateY(5px)}100%{opacity:1;transform:translateY(0)}}.window{animation:window-enter 180ms cubic-bezier(.23,1,.32,1)}.section{animation:window-enter 180ms cubic-bezier(.23,1,.32,1) both}.section:nth-of-type(1){animation-delay:40ms}.section:nth-of-type(2){animation-delay:80ms}.section:nth-of-type(3){animation-delay:120ms}
@media(prefers-reduced-motion:reduce){.window,.section{animation:none}.titlebar:after{animation:none}.pixel-light.pulse,.metric-value.changed{animation:status-pulse 180ms steps(1,end)}}
@media(max-width:720px){body{padding:10px}.overview,.form-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.menubar{overflow:auto}.status-cell:last-child{min-width:0}}@media(max-width:430px){.metrics{grid-template-columns:1fr}.password-row{flex-wrap:wrap}.password-row input{flex-basis:100%}.window-controls{display:none}}
</style>
</head>
<body><main class="window" aria-label="CheryNyxus 本地管理器">
<header class="titlebar"><span class="app-icon" aria-hidden="true"></span><span class="title">CheryNyxus 本地管理器</span><span class="window-controls" aria-hidden="true"><button type="button">_</button><button type="button">□</button><button type="button">×</button></span></header>
<nav class="menubar" aria-label="管理器菜单"><span class="menu-item">文件</span><span class="menu-item">查看</span><span class="menu-item">工具</span><span class="menu-item">帮助</span></nav>
${lanAccess ? '<div class="warning" role="alert"><strong>安全警告：</strong>局域网访问已开启。管理密钥是页面唯一保护，请仅在受信任网络使用。</div>' : ''}
<div class="content">
<section class="section"><div class="section-head"><h2>系统状态</h2><span class="section-label">Overview</span></div><div class="overview"><article class="summary"><div class="summary-title"><span id="availability-dot" class="pixel-light" aria-hidden="true"></span>运行状态</div><div id="availability" class="summary-value">读取中…</div><p id="availability-detail" class="summary-detail">正在读取后端可用性</p></article><article class="summary"><div class="summary-title"><span id="credential-dot" class="pixel-light" aria-hidden="true"></span>本地登录凭据</div><div id="credential-summary" class="summary-value">读取中…</div><p id="credentials" class="summary-detail">正在读取凭据状态</p></article></div></section>
<section class="section"><div class="section-head"><h2>后端运行状态与数据统计</h2><span class="section-label">Read-only monitor</span></div><div class="metrics"><div class="metric"><span class="metric-label">运行中任务</span><strong id="running-chats" class="metric-value">—</strong><span class="metric-note">当前正在执行的会话</span></div><div class="metric"><span class="metric-label">当前活跃调用</span><strong id="active-runs" class="metric-value">—</strong><span class="metric-note">当前进行中的调用</span></div><div class="metric"><span class="metric-label">已初始化会话</span><strong id="initialized-chats" class="metric-value">—</strong><span class="metric-note">后端内存中的会话</span></div><div class="metric"><span class="metric-label">内存使用</span><strong id="memory" class="metric-value">—</strong><span class="metric-note">管理器所在主机</span></div><div class="metric"><span class="metric-label">系统负载</span><strong id="load" class="metric-value">—</strong><span class="metric-note">1 分钟平均值</span></div><div class="metric"><span class="metric-label">后端进程</span><strong id="backend-process" class="metric-value">—</strong><span id="backend-process-note" class="metric-note">等待状态</span></div></div><div class="meta"><span>状态更新时间：<strong id="backend-updated">—</strong></span><span>后端地址：<strong id="backend-address">—</strong></span></div><ul id="processes" class="processes" aria-label="相关进程状态"></ul></section>
<section class="section"><div class="section-head"><h2>本地登录凭据</h2><span class="section-label">Credentials</span></div><form id="rotate"><div class="credentials-grid"><div class="form-grid"><div class="field"><label for="username">用户名（必填）</label><input id="username" autocomplete="username" placeholder="如 admin"></div><div class="field"><label for="password">密码（留空自动生成）</label><div class="password-row"><input id="password" type="password" autocomplete="new-password" placeholder="留空自动生成"><button id="toggle-password" class="retro-button" type="button">显示</button><button id="random-password" class="retro-button" type="button">随机生成</button></div></div></div></div><div class="button-row"><button id="refresh" class="retro-button" type="button">刷新状态</button><button type="submit" class="retro-button primary">保存凭据并生效</button></div><p id="message" class="message" role="status" aria-live="polite"></p></form></section>
</div><footer class="statusbar"><span class="status-cell"><strong id="status-state">READY</strong>　<span id="status-message">等待状态同步</span></span><span class="status-cell">刷新于 <strong id="last-updated">—</strong></span></footer>
</main>
<script>
const TOKEN_KEY='chery-manager-token';const $=id=>document.getElementById(id);const show=(id,text,cls='')=>{$(id).textContent=text;$(id).className=cls};const urlToken=new URLSearchParams(location.search).get('token')||'';if(urlToken){localStorage.setItem(TOKEN_KEY,urlToken);const u=new URL(location.href);u.searchParams.delete('token');history.replaceState(null,'',u.pathname+u.search+u.hash)}const tk=()=>{const value=localStorage.getItem(TOKEN_KEY);if(value)return value;const match=document.cookie.match(new RegExp('(?:^|; )'+TOKEN_KEY+'=([^;]+)'));return match?decodeURIComponent(match[1]):''};const renew=response=>{const next=response.headers.get('X-Chery-Manager-Token');if(next&&next!==tk())localStorage.setItem(TOKEN_KEY,next)};const formatTime=value=>value?new Date(value).toLocaleTimeString():'未知';const formatPercent=value=>typeof value==='number'?Math.round(value*100)+'%':'不可用';const formatLoad=value=>typeof value==='number'&&value>0?value.toFixed(2):'不可用';let loading=false;let previousMetrics={};
function markChanged(id,value){const node=$(id);if(node.textContent!==value&&node.textContent!=='—'){node.classList.remove('changed');void node.offsetWidth;node.classList.add('changed')}node.textContent=value;previousMetrics[id]=value}
function pulse(id,kind){const node=$(id);node.classList.remove(kind);void node.offsetWidth;node.classList.add(kind)}
function processItem(name,active){const item=document.createElement('li');item.textContent=name+'：'+(active?'运行中':'未运行');item.className=active?'ok':'warn';return item}
async function syncCredentials(){try{const response=await fetch('/api/credentials',{headers:{'X-Chery-Manager-Token':tk()}});if(!response.ok){show('credential-summary','需要密钥','warn');$('credential-dot').className='pixel-light warn';$('credentials').textContent='请从启动日志中的管理 URL 打开本页';return}renew(response);const credential=await response.json();const consistent=Boolean(credential.consistent);$('username').value=credential.username||'';$('password').value=credential.password||'';show('credential-summary',consistent?'已配置':'需要配置',consistent?'summary-value ok':'summary-value warn');$('credential-dot').className='pixel-light '+(consistent?'ok':'warn');$('credentials').textContent=credential.username?'凭据已加载到输入框':'尚未设置用户名'}catch{show('credential-summary','读取失败','error');$('credential-dot').className='pixel-light error';$('credentials').textContent='无法读取凭据'}}
async function load(){if(loading)return;loading=true;show('status-state','SYNC');$('status-message').textContent='正在读取状态…';try{const response=await fetch('/api/status',{headers:{'X-Chery-Manager-Token':tk()}});if(!response.ok)throw new Error('HTTP '+response.status);renew(response);const state=await response.json();const backend=state.backend||{};const agents=backend.agents||{};const system=state.system||{};const running=backend.status==='running';const oldAvailability=$('availability').textContent;show('availability',running?'后端在线':'后端未运行','summary-value '+(running?'ok':'warn'));$('availability-dot').className='pixel-light '+(running?'ok':'warn');$('availability-detail').textContent=running?'后端可以接受本机连接':'请确认后端进程和监听端口';if(oldAvailability!==$('availability').textContent)pulse('availability-dot','pulse');markChanged('running-chats',typeof agents.runningChats==='number'?String(agents.runningChats):'—');markChanged('active-runs',typeof agents.activeRuns==='number'?String(agents.activeRuns):'—');markChanged('initialized-chats',typeof agents.initializedChats==='number'?String(agents.initializedChats):'—');markChanged('memory',formatPercent(system.memoryUsedRatio));markChanged('load',formatLoad(system.load1));markChanged('backend-process',running?'运行中':'未运行');$('backend-process-note').textContent='后端状态';$('backend-updated').textContent=formatTime(backend.updatedAt);const webPort=backend.addresses&&backend.addresses.local?backend.addresses.local.httpPort:8183;$('backend-address').textContent=running?'http://'+location.hostname+':'+webPort:'不可用';const processes=$('processes');processes.textContent='';processes.append(processItem('后端',running));processes.append(processItem('中转 (rathole)',state.processes?.find(p=>p.name==='rathole')?.running));processes.append(processItem('中继 (relay)',state.relay?.status==='running'));$('last-updated').textContent=new Date().toLocaleTimeString();$('status-state').textContent='READY';$('status-message').textContent='状态已同步';await syncCredentials()}catch(error){show('message','读取失败：'+error.message,'error');$('status-state').textContent='ERROR';$('status-message').textContent='无法同步状态';$('last-updated').textContent='失败'}finally{loading=false}}
function randomPassword(){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);let value='';for(let index=0;index<12;index++)value+=String.fromCharCode(bytes[index]);return btoa(value).replace(/\\+/g,'-').replace(/\\//g,'_')}
$('random-password').onclick=()=>{$('password').value=randomPassword();show('message','已生成随机密码。','ok');$('status-message').textContent='密码已生成'};$('toggle-password').onclick=()=>{const input=$('password');const visible=input.type==='password';input.type=visible?'text':'password';$('toggle-password').textContent=visible?'隐藏':'显示'};$('refresh').onclick=load;$('rotate').onsubmit=async event=>{event.preventDefault();const username=$('username').value.trim();let password=$('password').value.trim();if(!username){show('message','用户名必填','error');return}if(!password){password=randomPassword();$('password').value=password}const button=$('rotate').querySelector('button[type=submit]');const label=button.textContent;button.disabled=true;button.textContent='处理中…';$('status-state').textContent='BUSY';try{const response=await fetch('/api/credentials/rotate',{method:'POST',headers:{'Content-Type':'application/json','X-Chery-Manager-Token':tk()},body:JSON.stringify({username,password})});if(!response.ok)throw new Error('HTTP '+response.status);renew(response);const result=await response.json();const verification=result.verification||{};if(verification.status==='verified'){show('message','凭据已更新并确认生效。','ok');$('status-message').textContent='凭据已保存';$('username').value=result.credentials?.username||username;$('password').value=result.credentials?.password||password}else if(verification.status==='unreachable'){show('message','凭据已更新，但后端暂时无法确认。','warn');$('status-message').textContent='凭据已保存，等待后端确认'}else{show('message','凭据已更新，但后端尚未确认。','warn');$('status-message').textContent='凭据已保存，等待确认'}await syncCredentials()}catch(error){show('message','更新失败：'+error.message,'error');$('status-state').textContent='ERROR';$('status-message').textContent='凭据保存失败'}finally{button.disabled=false;button.textContent=label}};load();setInterval(load,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
</script></body></html>`)
}
